#Default applications

EDITOR=nano
TERMINAL=alacritty
BROWSER=librewolf
ALT_BROWSER=brave

#XDG Home Dir Stuff

XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache
XDG_DATA_HOME=$HOME/.local/share
XDG_STATE_HOME=$HOME/.local/state
XDG_RUNTIME_DIR=/run/user/$UID

CARGO_HOME=$XDG_DATA_HOME"/cargo"

DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker

ELECTRUMDIR="$XDG_DATA_HOME/electrum"

FFMPEG_DATADIR="$XDG_CONFIG_HOME"/ffmpeg

GNUPGHOME="$XDG_DATA_HOME"/gnupg

GOPATH="$HOME"/development/go
GOBIN="$GOPATH"/bin

IPFS_PATH="$XDG_DATA_HOME"/ipfs

_JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

KODI_DATA=$XDG_DATA_HOME/kodi

PSQLRC="$XDG_CONFIG_HOME/pg/psqlrc"
PSQL_HISTORY="$XDG_STATE_HOME/psql_history"
PGPASSFILE="$XDG_CONFIG_HOME/pg/pgpass"
PGSERVICEFILE="$XDG_CONFIG_HOME/pg/pg_service.conf"

SCREENRC="$XDG_CONFIG_HOME"/screen/screenrc

TS3_CONFIG_DIR="$XDG_CONFIG_HOME/ts3client"

WGETRC="$XDG_CONFIG_HOME/wgetrc"

XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
XSERVERRC="$XDG_CONFIG_HOME"/X11/xserverrc

USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"
ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"
ERRFILE="$XDG+CACHE_HOME/X11/xsession-errors"

# Broken
#XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority

ZDOTDIR="$HOME"/.config/zsh
ZSH_CUSTOM="$ZDOTDIR"/OhMyZshCustom
HISTFILE="$XDG_STATE_HOME"/zsh/history
